name: isar_firebase_sync
description: Isar Firebase Sync.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  provider: ^6.0.5
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  firebase_remote_config: ^4.0.0
  firebase_analytics: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
